### ISSUE TITLE
[UAT-8] [Service Provider] User is able to sign up

### ISSUE THREAD

**Issue by rpgarde** [codesydney/migram-frontend#18]
Hello Tester,

Please add your comments here and we can discuss. 

### Current status
- [x] Testing started
- [x] Testing passed

**Comment by va-le-ria** [comment]
Able to create the account, unable to become a service provider -
I am able to get this far using the test verification tool -
![image](https://user-images.githubusercontent.com/100636497/158277939-1ee93c8c-5c87-4e50-afed-b9e3741939da.png)
When I click the Done button this appears - 
![1](https://user-images.githubusercontent.com/100636497/158277897-3ce0003e-e06a-4649-9a8a-0ecb5383e002.PNG)

**Comment by s-sinadinovic** [comment]
Looking at the URL it seems like it's incorrectly redirecting to localhost:3000/?success instead of migram-frontend-ruby.vercel.app/?success

I believe this is a field provided to the Stripe test environment so maybe @seqprav can look into it when he gets a chance

**Comment by seqprav** [comment]
Hi @va-le-ria ,

Can you please try registering a service provider in Stripe once again, and let me know if any issues? Many thanks for providing clear screenshots and testing notes.

Hi @s-sinadinovic ,

I've created 2 new environmental variables STRIPE_RETURN_URL & STRIPE_REFRESH_URL in Heroku to take care of this issue.
The values provided for these variables are
https://www.migram.com.au/account?success &  https://www.migram.com.au/account?failure

After clicking on Done on the Stripe website, the flow reverts back to the account screen from where the onboarding was triggered. Additional work may involve reading the query params (success & failure), so that the frontend to provide proper feedback to the user, but I'll leave this to your discretion and others.

cc: @engramar , @rpgarde

**Comment by engramar** [comment]
Enhancement request raised in #28
