### ISSUE TITLE
[UAT Finding per UAT-4] No confirmation after adding a new credit card

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#29]
As per @moises962 

> Entering a random card number produces an error message.
When test card is entered correctly, there is no message to confirm that it has been accepted. It would be good to have a message to say card has been accepted.
Rgds,
Moises

**Comment by rpgarde** [comment]
Added confirmation message which redirects you to Account afterwards
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/80566196/162663093-2c28e3b4-4492-4d71-98b4-227f784e3eb3.png">

Added error handling which passes in the message from stripe if it fails
<img width="993" alt="image" src="https://user-images.githubusercontent.com/80566196/162663119-b5e504ee-f270-45c8-8b8a-dff7ded154e0.png">

Otherwise if no error message, generic "error when adding a card" 
<img width="937" alt="image" src="https://user-images.githubusercontent.com/80566196/162662315-8242e068-81f4-4c0f-a335-6d560b9f2b93.png">

**Comment by rpgarde** [comment]
@engramar @moises962 I pushed an update (see screenshots above) please test it out and if all good, close this issue and issue #14

**Comment by engramar** [comment]
Confirmed working by @va-le-ria after the retest.
