### ISSUE TITLE
[UAT Finding per UAT-7] No confirmation after job has been marked as completed

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#30]
As per @va-le-ria 
> No issues until marking as completed as the service provider. I click it and nothing happens, when I click on the "completed" tab nothing happens. When I refresh the page nothing changes.

**Comment by s-sinadinovic** [comment]
I just had a chance to look at the code, it seems like there is a difference between the `status` property of an `offer` depending on whether it is returned using `getOffers` (returns `status: accepted`) and `getOffer` (returns `status: completed`) that is causing the `offer` to show as `accepted` instead of `completed`.

I'm currently writing a work-around for the frontend but it requires making N+1 calls to return the correct `status` rather than having the correct status returned with a single `getOffers` call. I'm happy to move ahead with solving this on the frontend but it might be worthwhile also fixing this on the backend so that an `offer` always returns the correct `status`.

Sorry for delay (and ramblings), I should have the change pushed by EOD 🙂

**Comment by davidtaing** [comment]
Sorry, it looks like this one has been doubled up.

Related: #36

**Comment by davidtaing** [comment]
Also, @s-sinadinovic, well done on thinking about the N+1 Calls. I agree with you that it's worthwhile at looking at the backend so that we can avoid hitting the database N+1 times.

I'll have a video call discussion with Praveen at some point over the next week.
