### ISSUE TITLE
Bug: Homepage breaks on size 324px

### ISSUE THREAD

**Issue by composerrequirer** [codesydney/migram-frontend#61]
It's caused by the font size of "Illawarra Multicultural Services" title.

**Comment by davidtaing** [comment]
Hi @composerrequirer,
Can you please provide some more information? You have to think about the other person's shoes. The more information you give, the easier it will be for a reviewer to find your bug.

I know that this issue is on the smaller side, and doing this is probably overkill, but I feel that it is important to establish good practices for all issues.

Can you please add the following?
- [ ] Expected Behaviour
- [ ] Actual Behaviour
- [ ] Screenshots
- [ ] Steps to Reproduce

**Comment by composerrequirer** [comment]
I made a pull request with the fixes, but it's not showing here, I think I made some mistake.

**Comment by davidtaing** [comment]
You need to put the hash before the issue number. Can you please edit your original post?

**Comment by composerrequirer** [comment]
Well, do really want me to remove the changes, or can I just leave it?

**Comment by davidtaing** [comment]
I would like you to because we won't be using the styles for the width < 283px. I can't even think of a phone that has a viewport width of 280px. The iPhone which was released in 2012 has a viewport of 320px.

On top of that, there is a good chance that we will redo the landing page. I'm in the process of rewriting the sign up page for a Customer. <img width="959" alt="chrome_gglaj90d2i" src="https://user-images.githubusercontent.com/8443215/188198462-a819d3ca-d6ab-4a7a-9f02-887a38bbf540.png">

What would you like me to do?

**Comment by composerrequirer** [comment]
Ok, I'll remove the changes and make another pull request.

**Comment by composerrequirer** [comment]
Actually, it was breaking on 324px, I'll keep the changes for the font size of that <h2> tag and just remove the changes for the header, is that ok?

**Comment by composerrequirer** [comment]
Actually, it was breaking on 324px, I'll keep the changes for the font size of that

**Comment by composerrequirer** [comment]
Actually, it was breaking on 324px, I'll keep the changes I made on the font size of that title, and just remove the changes I did in the header, is that ok?

**Comment by davidtaing** [comment]
That should be fine. Please go ahead. Can you please also adjust the subheading sizes as well? So the heading stays bigger than the subheading.

Thanks.

**Comment by composerrequirer** [comment]
Can I close this issue?

**Comment by davidtaing** [comment]
Up to you. If you close it, the code won't be merged into main.

**Comment by davidtaing** [comment]
Closing this issue as we are looking into redoing the landing page.
